{
 "title": "Artipie metrics r2 (InfluxDB)",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"up\")\r\n"
    }
   ]
  },
  {
   "title": "Response body size and chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_response_body_size_bytes_sum\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Requests counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_request_counter_total\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Response.send execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_response_send_seconds_max\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Connection.accept execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_connection_accept_seconds_sum\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Slice.response execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_slice_response_seconds_max\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Time to read value from storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_value_seconds_max\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Time to save storage value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_save_seconds_sum\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Storage value size and chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_value_size_bytes_max\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Storage exists operation time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_exists_seconds_max\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Storage move operation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_move_seconds_sum\")\r\n"
    }
   ]
  },
  {
   "title": "Storage list operation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_list_seconds_sum\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Storage delete operation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_delete_seconds_sum\")\r\n"
    }
   ]
  },
  {
   "title": "Storage metadata operation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_metadata_seconds_sum\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Storage exclusively operation seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_exclusively_seconds_sum\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Storage deleteAll operation seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.job == \"artipie_metrics\" and r._field == \"artipie_storage_deleteAll_seconds_sum\")\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\r\n  |> group()\r\n"
    }
   ]
  }
 ]
}