---
version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    volumes:
      - ./conf/:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  artipie:
    image: artipie/artipie:1.0-SNAPSHOT
    container_name: artipie
    volumes:
      - "./artipie/etc:/etc/artipie"
      - "./artipie/var:/var/artipie"
    environment:
      - JVM_ARGS=
        -javaagent:/etc/artipie/jmx_prometheus_javaagent-0.17.2.jar=${JMX_AGENT}:/etc/artipie/jmx-agent.yml 
        -agentlib:jdwp=transport=dt_socket,server=y,address=*:${JDEBUG},suspend=n -Djava.rmi.server.hostname=localhost 
        -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=${JMX_PORT} 
        -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} -Dcom.sun.management.jmxremote.local.only=false 
        -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    ports:
      - "8080:8080"
      - "8087:8087" #vertx metrics
      - "${JDEBUG}:${JDEBUG}"
      - "${JMX_PORT}:${JMX_PORT}"
      - "${JMX_AGENT}:${JMX_AGENT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #profiles:
    #  - dontstart
  grafana:
    image: grafana/grafana:9.2.4
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
